export const COPY = {
  en: {
    title: "Local model hub",
    quickStartTitle: "Recommended for this computer",
    advancedTitle: "Other choices & advanced setup",
    subtitle: "Models that run on your computer.",
    searchPlaceholder: "Search models",
    filters: {
      all: "All",
      recommended: "Recommended",
      installed: "Installed",
      compatible: "Compatible",
      "planner-llm": "Text",
      vision: "Vision",
      "image-gen": "Image",
    },    summaryReady: (count: number) => `${count} installed`,
    summaryFit: (count: number) => `${count} fit this machine`,
    summaryRunning: (label: string | null) => (label ? `Running ${label}` : "No text model running"),
    summarySelected: (label: string | null) => (label ? `Selected for tasks: ${label}` : "Selected for tasks: none"),
    noResults: "No model matches this search.",
    fileProgress: (i: number, n: number) => `File ${i} / ${n}`,
    installingPercent: (pct: number | null) => (pct !== null ? `${pct}%` : "Preparing"),
    speed: (bps: number) => {
      if (bps >= 1_000_000) return `${(bps / 1_000_000).toFixed(1)} MB/s`;
      if (bps >= 1000) return `${(bps / 1000).toFixed(0)} KB/s`;
      return `${bps} B/s`;
    },
    stateLabels: {
      not_downloaded: "Not installed",
      partial: "Partial",
      downloading: "Installing",
      downloaded: "Ready",
      missing_runtime: "Local AI not ready",
      hardware_unfit: "Not compatible",
      planned: "Planned",
      error: "Error",
      canceled: "Paused",
    },
    primaryInstall: "Install",
    primaryInstallRun: "Install & run",
    primaryResume: "Resume",
    primaryRun: "Run",
    primaryRunning: "Running",
    primaryReadyStudio: "Ready in Studio",
    primaryDiagnostics: "Diagnose",
    actionCancel: "Cancel",
    actionRetry: "Retry",
    actionRefresh: "Refresh",
    actionProbe: "Connect local AI",
    actionImport: "Import model",
    actionChooseFile: "Paste path",
    actionImportFile: "Register path",
    actionQueueUrl: "Download URL",
    queueTitle: "Install queue",
    importTitle: "Import or connect",
    importFileLabel: "Local model path",
    importUrlLabel: "Hugging Face file URL",
    importRuntimeLabel: "Model type",
    importDone: "Model imported. Refreshing model center.",
    importQueued: "Download queued in the install queue.",
    importError: "Import failed.",
    importStalled: "Download stalled — no progress for a while. Check Local AI status and your connection, then try again.",
    externalTitle: "Connected local AI",
    externalEmpty: "No Ollama models detected. To connect LM Studio or other local AI, add it under Service connections.",
    detectedModels: (count: number) => `${count} detected models`,
    disabledNoRam: (need: number) => `Requires ${need} GB RAM`,
    disabledAppleSilicon: "Apple Silicon only",
    disabledDisk: (need: number) => `Requires ~${need} GB free disk`,
    disabledPlanned: "Not available yet",
    mlxDownloading: "Downloading model",
    mlxLoading: "Loading model",
    runtimeMissing: "Local AI isn't ready yet. Check Local AI status.",
    activateFailed: "Could not start this model. Check Local AI status and try again.",
    tags: {
      text: "Text",
      planner: "Planner",
      balanced: "Balanced",
      "apple-silicon": "Apple Silicon",
      fast: "Fast",
      "low-ram": "Low RAM",
      vision: "Vision",
      "external-runtime": "External",
      image: "Image",
      quality: "Quality",
      object: "Object",
      stable: "Stable",
      imported: "Imported",
    },
    accel: {
      metal: "Apple Silicon · Metal",
      cuda: "CUDA",
      vulkan: "Vulkan",
      cpu: "CPU only — slower",
    },
    accelRam: (ram: number, disk: number) =>
      `${ram} GB RAM · ${disk > 0 ? `${disk} GB free` : "disk unknown"}`,
    runtimeRunning: "Running",
    runtimeInstalledNotRunning: "Not running",
    runtimeNotInstalled: "Not installed",
    runtimeOpenApp: "Open App",
    runtimeDownload: "Download",
    runtimeConnected: "Connected",
    runtimeUnavailableTitle: "Run models on your own computer",
    runtimeUnavailableDescription:
      "Open the Lunery desktop app to install and run image and text models locally — no usage limits, fully offline. Until then, connect a cloud API key to keep creating right now.",
    runtimeUnavailablePrimaryAction: "Get the desktop app",
    runtimeUnavailableProviderAction: "Or use a cloud key now",
    runtimeUnavailableCloudHint:
      "Cloud keys are saved securely and keep working once the desktop app runs.",
    runtimeUnavailableEngineNote: "Runs locally on your computer, fully offline.",
  },
  zh: {
    title: "本地模型中心",
    quickStartTitle: "适合这台电脑的推荐",
    advancedTitle: "其他选择与高级设置",
    subtitle: "在你电脑上运行的模型。",
    searchPlaceholder: "搜索模型",
    filters: {
      all: "全部",
      recommended: "推荐",
      installed: "已安装",
      compatible: "适配本机",
      "planner-llm": "文本",
      vision: "视觉",
      "image-gen": "图片",
    },
    summaryReady: (count: number) => `已安装 ${count} 个`,
    summaryFit: (count: number) => `${count} 个适配本机`,
    summaryRunning: (label: string | null) => (label ? `正在运行 ${label}` : "未运行文本模型"),
    summarySelected: (label: string | null) => (label ? `已选为任务模型：${label}` : "已选为任务模型：无"),
    noResults: "没有匹配的模型。",
    fileProgress: (i: number, n: number) => `文件 ${i} / ${n}`,
    installingPercent: (pct: number | null) => (pct !== null ? `${pct}%` : "准备中"),
    speed: (bps: number) => {
      if (bps >= 1_000_000) return `${(bps / 1_000_000).toFixed(1)} MB/s`;
      if (bps >= 1000) return `${(bps / 1000).toFixed(0)} KB/s`;
      return `${bps} B/s`;
    },
    stateLabels: {
      not_downloaded: "未安装",
      partial: "部分安装",
      downloading: "安装中",
      downloaded: "已就绪",
      missing_runtime: "本地 AI 未就绪",
      hardware_unfit: "不兼容",
      planned: "规划中",
      error: "错误",
      canceled: "已暂停",
    },
    primaryInstall: "安装",
    primaryInstallRun: "安装并运行",
    primaryResume: "继续",
    primaryRun: "运行",
    primaryRunning: "运行中",
    primaryReadyStudio: "Studio 可用",
    primaryDiagnostics: "诊断",
    actionCancel: "取消",
    actionRetry: "重试",
    actionRefresh: "刷新",
    actionProbe: "连接本地 AI",
    actionImport: "导入模型",
    actionChooseFile: "粘贴路径",
    actionImportFile: "注册路径",
    actionQueueUrl: "下载 URL",
    queueTitle: "安装队列",
    importTitle: "导入或连接",
    importFileLabel: "本地模型路径",
    importUrlLabel: "Hugging Face 文件 URL",
    importRuntimeLabel: "模型类型",
    importDone: "模型已导入，正在刷新模型中心。",
    importQueued: "下载已加入安装队列。",
    importError: "导入失败。",
    importStalled: "下载长时间无进展，已停止。请检查本地 AI 状态与网络连接后重试。",
    externalTitle: "已连接的本地 AI",
    externalEmpty: "未检测到 Ollama 模型。要连接 LM Studio 等其他本地 AI，请在「服务连接」中添加。",
    detectedModels: (count: number) => `检测到 ${count} 个模型`,
    disabledNoRam: (need: number) => `需要 ${need} GB 内存`,
    disabledAppleSilicon: "仅支持 Apple Silicon",
    disabledDisk: (need: number) => `需要约 ${need} GB 可用磁盘`,
    disabledPlanned: "暂未支持",
    mlxDownloading: "下载模型中",
    mlxLoading: "加载中",
    runtimeMissing: "本地 AI 尚未就绪，请检查本地 AI 状态。",
    activateFailed: "无法启动该模型，请检查本地 AI 状态后重试。",
    tags: {
      text: "文本",
      planner: "规划",
      balanced: "均衡",
      "apple-silicon": "Apple 芯片",
      fast: "快速",
      "low-ram": "低内存",
      vision: "视觉",
      "external-runtime": "外部",
      image: "图片",
      quality: "高质量",
      object: "图像创作",
      stable: "稳定",
      imported: "已导入",
    },
    accel: {
      metal: "Apple Silicon · Metal",
      cuda: "CUDA",
      vulkan: "Vulkan",
      cpu: "仅 CPU（较慢）",
    },
    accelRam: (ram: number, disk: number) =>
      `${ram} GB 内存 · ${disk > 0 ? `${disk} GB 可用` : "磁盘未知"}`,
    runtimeRunning: "运行中",
    runtimeInstalledNotRunning: "未运行",
    runtimeNotInstalled: "未安装",
    runtimeOpenApp: "打开应用",
    runtimeDownload: "下载",
    runtimeConnected: "已连接",
    runtimeUnavailableTitle: "在你自己的电脑上运行模型",
    runtimeUnavailableDescription:
      "打开 Lunery 桌面应用，即可在本地安装并运行图片与文本模型——没有用量限制、完全离线。在那之前，连接一个云端 API key 就能立即继续创作。",
    runtimeUnavailablePrimaryAction: "获取桌面应用",
    runtimeUnavailableProviderAction: "或现在用云端 key",
    runtimeUnavailableCloudHint: "云端 key 会被安全保存，桌面应用运行后依旧可用。",
    runtimeUnavailableEngineNote: "在你的电脑上本地运行，完全离线。",
  },
  // Formatter-valued copy remains local to this panel.
  zhTW: {
    title: "本地模型中心",
    quickStartTitle: "適合這台電腦的推薦",
    advancedTitle: "其他選擇與進階設定",
    subtitle: "在你電腦上執行的模型。",
    searchPlaceholder: "搜尋模型",
    filters: {
      all: "全部",
      recommended: "推薦",
      installed: "已安裝",
      compatible: "適配本機",
      "planner-llm": "文字",
      vision: "視覺",
      "image-gen": "圖片",
    },
    summaryReady: (count: number) => `已安裝 ${count} 個`,
    summaryFit: (count: number) => `${count} 個適配本機`,
    summaryRunning: (label: string | null) => (label ? `正在執行 ${label}` : "未執行文字模型"),
    summarySelected: (label: string | null) => (label ? `已選為任務模型：${label}` : "已選為任務模型：無"),
    noResults: "沒有符合的模型。",
    fileProgress: (i: number, n: number) => `檔案 ${i} / ${n}`,
    installingPercent: (pct: number | null) => (pct !== null ? `${pct}%` : "準備中"),
    speed: (bps: number) => {
      if (bps >= 1_000_000) return `${(bps / 1_000_000).toFixed(1)} MB/s`;
      if (bps >= 1000) return `${(bps / 1000).toFixed(0)} KB/s`;
      return `${bps} B/s`;
    },
    stateLabels: {
      not_downloaded: "未安裝",
      partial: "部分安裝",
      downloading: "安裝中",
      downloaded: "已就緒",
      missing_runtime: "本地 AI 未就緒",
      hardware_unfit: "不相容",
      planned: "規劃中",
      error: "錯誤",
      canceled: "已暫停",
    },
    primaryInstall: "安裝",
    primaryInstallRun: "安裝並執行",
    primaryResume: "繼續",
    primaryRun: "執行",
    primaryRunning: "執行中",
    primaryReadyStudio: "Studio 可用",
    primaryDiagnostics: "診斷",
    actionCancel: "取消",
    actionRetry: "重試",
    actionRefresh: "重新整理",
    actionProbe: "連接本地 AI",
    actionImport: "匯入模型",
    actionChooseFile: "貼上路徑",
    actionImportFile: "註冊路徑",
    actionQueueUrl: "下載 URL",
    queueTitle: "安裝佇列",
    importTitle: "匯入或連接",
    importFileLabel: "本地模型路徑",
    importUrlLabel: "Hugging Face 檔案 URL",
    importRuntimeLabel: "模型類型",
    importDone: "模型已匯入，正在重新整理模型中心。",
    importQueued: "下載已加入安裝佇列。",
    importError: "匯入失敗。",
    importStalled: "下載長時間無進展，已停止。請檢查本地 AI 狀態與網路連線後重試。",
    externalTitle: "已連接的本地 AI",
    externalEmpty: "未檢測到 Ollama 模型。要連接 LM Studio 等其他本地 AI，請在「服務連接」中新增。",
    detectedModels: (count: number) => `檢測到 ${count} 個模型`,
    disabledNoRam: (need: number) => `需要 ${need} GB 記憶體`,
    disabledAppleSilicon: "僅支援 Apple Silicon",
    disabledDisk: (need: number) => `需要約 ${need} GB 可用磁碟`,
    disabledPlanned: "暫未支援",
    mlxDownloading: "下載模型中",
    mlxLoading: "載入中",
    runtimeMissing: "本地 AI 尚未就緒，請檢查本地 AI 狀態。",
    activateFailed: "無法啟動該模型，請檢查本地 AI 狀態後重試。",
    tags: {
      text: "文字",
      planner: "規劃",
      balanced: "均衡",
      "apple-silicon": "Apple 晶片",
      fast: "快速",
      "low-ram": "低記憶體",
      vision: "視覺",
      "external-runtime": "外部",
      image: "圖片",
      quality: "高品質",
      object: "圖像創作",
      stable: "穩定",
      imported: "已匯入",
    },
    accel: {
      metal: "Apple Silicon · Metal",
      cuda: "CUDA",
      vulkan: "Vulkan",
      cpu: "僅 CPU（較慢）",
    },
    accelRam: (ram: number, disk: number) =>
      `${ram} GB 記憶體 · ${disk > 0 ? `${disk} GB 可用` : "磁碟未知"}`,
    runtimeRunning: "執行中",
    runtimeInstalledNotRunning: "未執行",
    runtimeNotInstalled: "未安裝",
    runtimeOpenApp: "開啟應用",
    runtimeDownload: "下載",
    runtimeConnected: "已連接",
    runtimeUnavailableTitle: "在你自己的電腦上執行模型",
    runtimeUnavailableDescription:
      "開啟 Lunery 桌面應用程式，即可在本機安裝並執行圖片與文字模型——沒有用量限制、完全離線。在那之前，連接一個雲端 API key 就能立即繼續創作。",
    runtimeUnavailablePrimaryAction: "取得桌面應用程式",
    runtimeUnavailableProviderAction: "或現在用雲端 key",
    runtimeUnavailableCloudHint: "雲端 key 會被安全保存，桌面應用程式執行後依舊可用。",
    runtimeUnavailableEngineNote: "在你的電腦上本地執行，完全離線。",
  },
} as const;

export type CopyShape = (typeof COPY)["en"] | (typeof COPY)["zh"] | (typeof COPY)["zhTW"];

export const MODEL_DETAILS = {
  en: {
    "qwen3.6-35b-a3b-ud-q4-k-m": {
      bestFor: "High-quality local planning, reasoning, and canvas instruction work on high-memory machines.",
      why: "Current high-download Qwen MoE GGUF, selected as the main hot text recommendation.",
    },
    "qwen3.6-27b-q4": {
      bestFor: "Current local text planning when the larger hot model is too heavy.",
      why: "Keeps the model hub current while staying within a more realistic single-file install size.",
    },
    "qwen3.6-27b-mlx-optiq-4bit": {
      bestFor: "Current Apple Silicon text planning with MLX acceleration.",
      why: "Mac-native current Qwen path for users who want a resident local engine.",
    },
    "deepseek-v4-flash-iq2xxs": {
      bestFor: "High-memory machines that need a hot DeepSeek local text model.",
      why: "Included for current popularity and official V4 Flash lineage; ordinary laptops are blocked by the RAM gate.",
    },
    "flux2-dev-q4": {
      bestFor: "Current local image generation for creator workflows.",
      why: "Current FLUX row selected over older image baselines.",
    },
    "qwen2.5-7b-instruct-q4": {
      bestFor: "Fast low-RAM text option.",
      why: "Kept as a runnable option for smaller machines and existing local setups.",
    },
    "qwen2.5-7b-instruct-mlx": {
      bestFor: "Fast Apple Silicon text option.",
      why: "Kept as a Mac-friendly local option for smaller machines and existing setups.",
    },
    "llama-3.2-3b-instruct-q4": {
      bestFor: "Small low-RAM text option.",
      why: "Kept as a lightweight local option for older or smaller machines.",
    },
    "flux1-schnell-q4": {
      bestFor: "Quality image option for smaller installs.",
      why: "Kept as a runnable image path when the newest FLUX kit is too large.",
    },
    "sdxl-base-1.0": {
      bestFor: "Stable image option with a smaller download.",
      why: "Kept as a familiar image baseline that is easier to install than the newest kit.",
    },
    "sd15-emaonly": {
      bestFor: "Fast low-RAM image option.",
      why: "Kept as the smallest first-run image path for quick local creation.",
    },
  },
  zh: {
    "qwen3.6-35b-a3b-ud-q4-k-m": {
      bestFor: "适合高内存机器上的本地规划、推理和画布指令理解。",
      why: "当前高下载量的 Qwen MoE GGUF，作为热门文本首选。",
    },
    "qwen3.6-27b-q4": {
      bestFor: "当更大的热门模型过重时，用作当前代本地文本规划。",
      why: "保持模型中心当前代，同时维持更现实的单文件安装体积。",
    },
    "qwen3.6-27b-mlx-optiq-4bit": {
      bestFor: "适合 Apple 芯片的当前代 MLX 文本规划。",
      why: "给需要本机常驻文本引擎的 Mac 用户保留当前代路径。",
    },
    "deepseek-v4-flash-iq2xxs": {
      bestFor: "适合高内存机器的热门 DeepSeek 本地文本模型。",
      why: "因当前热度和官方 V4 Flash 来源纳入；普通笔记本会被 RAM 门槛拦住。",
    },
    "flux2-dev-q4": {
      bestFor: "适合创作者流程的当前代本地图片生成。",
      why: "使用当前 FLUX 行，不再把旧图片基线作为推荐。",
    },
    "qwen2.5-7b-instruct-q4": {
      bestFor: "适合低内存机器的快速文本选项。",
      why: "作为小内存机器和已有本地配置的可运行选项保留。",
    },
    "qwen2.5-7b-instruct-mlx": {
      bestFor: "适合 Apple 芯片的快速文本选项。",
      why: "作为更适合小内存 Mac 的本地选项保留。",
    },
    "llama-3.2-3b-instruct-q4": {
      bestFor: "适合低内存机器的小型文本选项。",
      why: "作为老机器或小内存机器的轻量本地选项保留。",
    },
    "flux1-schnell-q4": {
      bestFor: "安装体积更小的高质量图片选项。",
      why: "当最新 FLUX 套件过大时，保留这条可运行的图片路径。",
    },
    "sdxl-base-1.0": {
      bestFor: "下载更小的稳定图片选项。",
      why: "作为熟悉且更容易安装的图片基线保留。",
    },
    "sd15-emaonly": {
      bestFor: "适合低内存机器的快速图片选项。",
      why: "作为最小的首次本地出图路径保留。",
    },
  },
  zhTW: {
    "qwen3.6-35b-a3b-ud-q4-k-m": {
      bestFor: "適合高記憶體機器上的本地規劃、推理和畫布指令理解。",
      why: "當前高下載量的 Qwen MoE GGUF，作為熱門文字首選。",
    },
    "qwen3.6-27b-q4": {
      bestFor: "當更大的熱門模型過重時，用作當前代本地文字規劃。",
      why: "保持模型中心當前代，同時維持更實際的單一檔案安裝體積。",
    },
    "qwen3.6-27b-mlx-optiq-4bit": {
      bestFor: "適合 Apple 晶片的當前代 MLX 文字規劃。",
      why: "給需要本機常駐文字引擎的 Mac 使用者保留當前代路徑。",
    },
    "deepseek-v4-flash-iq2xxs": {
      bestFor: "適合高記憶體機器的熱門 DeepSeek 本地文字模型。",
      why: "因當前熱度和官方 V4 Flash 來源納入；普通筆電會被 RAM 門檻擋住。",
    },
    "flux2-dev-q4": {
      bestFor: "適合創作者流程的當前代本地圖片生成。",
      why: "使用當前 FLUX 列，不再把舊圖片基線作為推薦。",
    },
    "qwen2.5-7b-instruct-q4": {
      bestFor: "適合低記憶體機器的快速文字選項。",
      why: "作為小記憶體機器和既有本機設定的可執行選項保留。",
    },
    "qwen2.5-7b-instruct-mlx": {
      bestFor: "適合 Apple 晶片的快速文字選項。",
      why: "作為更適合小記憶體 Mac 的本機選項保留。",
    },
    "llama-3.2-3b-instruct-q4": {
      bestFor: "適合低記憶體機器的小型文字選項。",
      why: "作為舊機器或小記憶體機器的輕量本機選項保留。",
    },
    "flux1-schnell-q4": {
      bestFor: "安裝體積更小的高品質圖片選項。",
      why: "當最新 FLUX 套件過大時，保留這條可執行的圖片路徑。",
    },
    "sdxl-base-1.0": {
      bestFor: "下載更小的穩定圖片選項。",
      why: "作為熟悉且更容易安裝的圖片基線保留。",
    },
    "sd15-emaonly": {
      bestFor: "適合低記憶體機器的快速圖片選項。",
      why: "作為最小的首次本機出圖路徑保留。",
    },
  },
} as const;
