import { BYOK_PROVIDERS } from "@/lib/byok-providers";

export const PROVIDER_ORDER = BYOK_PROVIDERS.map((p) => p.id);
export const DEFAULT_ENDPOINTS: Record<string, string> = Object.fromEntries(
  BYOK_PROVIDERS.map((p) => [p.id, p.defaultEndpoint]),
);

export const COPY = {
  en: {
    title: "Desktop app",
    subtitle: "Local AI",
    providerTitle: "Connect a cloud service",
    providerSubtitle: "Choose a service and paste your key. It stays on this computer.",
    providerLabel: "Service",
    endpoint: "Server address",
    advancedTitle: "Advanced settings",
    modelId: "Model ID",
    modelIdHint: "Copy a current model ID from the provider.",
    openModelList: "Open official model list",
    modelRoleText: "Text model",
    modelRoleImage: "Image model",
    modelRoleVideo: "Video model",
    modelRole3d: "3D model",
    key: "API key",
    keyPlaceholder: "Paste your API key",
    save: "Save locally",
    remove: "Remove",
    moreActions: "More actions",
    managedByEnvironment: "This key is managed outside Lunery.",
    removeConfirmTitle: "Remove this connection?",
    removeConfirmDescription: "The saved key and connection settings for this service will be removed from this computer.",
    cancel: "Cancel",
    test: "Test",
    testing: "Testing…",
    testOk: "Valid",
    testFail: "Check failed: {reason}",
    saved: "Saved locally",
    savedOk: "Connection saved.",
    endpointRequired: "Enter a server address to save.",
    modelIdRequired: "Enter a model ID to save.",
    keyRequired: "Enter an API key to save.",
    saveFailed: "Couldn't save. Please try again.",
    savePartial: "The key was saved, but the connection settings weren't. Save again to finish.",
    removeFailed: "Couldn't fully remove this connection. Try again.",
    env: "Detected from environment",
    keychain: "Saved securely",
    keychainUnavailable: "System keychain unavailable",
    secretStored: "Saved securely",
    secretStoredEnv: "Provided by environment",
    bridgeChecking: "Checking desktop connection…",
    unavailable: "Open the desktop app to save keys.",
    bridgeDownTitle: "Desktop app not running",
    bridgeDownText: "Open the app to connect services and save keys.",
    notConnected: "Not connected",
    capabilityText: "text",
    capabilityImage: "image",
    capabilityVideo: "video",
    capability3d: "3D",
    runtimeTitle: "Local AI",
    profileTitle: "Local data folder",
    profileEmptyText: "Open the app to locate local data.",
    openProfileFolder: "Open",
    openingProfileFolder: "Opening…",
    openProfileFolderFailed: "Couldn't open the local data folder.",
    openProfileFolderOk: "Local data folder opened.",
    modelStoreTitle: "Model stores",
    runtimeEmptyTitle: "No status yet",
    runtimeEmptyText: "Open the app to check local models.",
    modelStoreEmptyTitle: "No model store status",
    modelStoreEmptyText: "Your model folders appear here.",
    available: "Available",
    missing: "Not found",
    locked: "Keys stay on this computer",
    runtimeAvailable: "Available",
    runtimeModels: "models",
    runtimeProbing: "Probing…",
    systemDetailsTitle: "Storage & connection details",
  },
  "zh-CN": {
    title: "桌面应用",
    subtitle: "本地 AI",
    providerTitle: "连接云端服务",
    providerSubtitle: "选择服务并粘贴密钥；密钥只保存在这台电脑上。",
    providerLabel: "服务",
    endpoint: "服务器地址",
    advancedTitle: "高级设置",
    modelId: "模型 ID",
    modelIdHint: "从服务商复制当前模型 ID。",
    openModelList: "打开官方模型列表",
    modelRoleText: "文本模型",
    modelRoleImage: "图像模型",
    modelRoleVideo: "视频模型",
    modelRole3d: "3D 模型",
    key: "API 密钥",
    keyPlaceholder: "粘贴你的 API 密钥",
    save: "保存到本机",
    remove: "移除",
    moreActions: "更多操作",
    managedByEnvironment: "这个密钥由 Lunery 外部管理。",
    removeConfirmTitle: "移除这个连接？",
    removeConfirmDescription: "这项服务保存的密钥与连接设置将从这台电脑移除。",
    cancel: "取消",
    test: "测试",
    testing: "测试中…",
    testOk: "有效",
    testFail: "测试失败：{reason}",
    saved: "已保存在本机",
    savedOk: "连接已保存。",
    endpointRequired: "请先填写服务器地址再保存。",
    modelIdRequired: "请先填写模型 ID 再保存。",
    keyRequired: "请先填写 API 密钥再保存。",
    saveFailed: "保存失败，请重试。",
    savePartial: "密钥已保存，但连接设置未保存。请再次保存以完成连接。",
    removeFailed: "未能完整移除这个连接，请重试。",
    env: "检测到环境变量",
    keychain: "已安全保存",
    keychainUnavailable: "系统钥匙串不可用",
    secretStored: "已安全保存",
    secretStoredEnv: "来自环境变量",
    bridgeChecking: "正在检查桌面连接…",
    unavailable: "打开桌面应用保存密钥。",
    bridgeDownTitle: "桌面应用未运行",
    bridgeDownText: "打开应用即可连接服务并保存密钥。",
    notConnected: "未连接",
    capabilityText: "文本",
    capabilityImage: "图像",
    capabilityVideo: "视频",
    capability3d: "3D",
    runtimeTitle: "本地 AI",
    profileTitle: "本机数据目录",
    profileEmptyText: "打开应用即可定位本机数据。",
    openProfileFolder: "打开",
    openingProfileFolder: "打开中…",
    openProfileFolderFailed: "无法打开本机数据目录。",
    openProfileFolderOk: "已打开本机数据目录。",
    modelStoreTitle: "模型目录",
    runtimeEmptyTitle: "暂无状态",
    runtimeEmptyText: "打开应用查看本地模型。",
    modelStoreEmptyTitle: "暂无模型目录状态",
    modelStoreEmptyText: "你的模型目录会显示在这里。",
    available: "已存在",
    missing: "未发现",
    locked: "密钥只保存在本机",
    runtimeAvailable: "已连接",
    runtimeModels: "个模型",
    runtimeProbing: "探测中…",
    systemDetailsTitle: "存储与连接详情",
  },
  "zh-TW": {
    title: "桌面應用",
    subtitle: "本地 AI",
    providerTitle: "連接雲端服務",
    providerSubtitle: "選擇服務並貼上金鑰；金鑰只儲存在這台電腦上。",
    providerLabel: "服務",
    endpoint: "伺服器位址",
    advancedTitle: "進階設定",
    modelId: "模型 ID",
    modelIdHint: "從服務商複製目前的模型 ID。",
    openModelList: "打開官方模型列表",
    modelRoleText: "文字模型",
    modelRoleImage: "圖像模型",
    modelRoleVideo: "影片模型",
    modelRole3d: "3D 模型",
    key: "API 金鑰",
    keyPlaceholder: "貼上你的 API 金鑰",
    save: "儲存到本機",
    remove: "移除",
    moreActions: "更多操作",
    managedByEnvironment: "這個金鑰由 Lunery 外部管理。",
    removeConfirmTitle: "移除這個連線？",
    removeConfirmDescription: "這項服務儲存的金鑰與連線設定將從這台電腦移除。",
    cancel: "取消",
    test: "測試",
    testing: "測試中…",
    testOk: "有效",
    testFail: "測試失敗：{reason}",
    saved: "已儲存在本機",
    savedOk: "連線已儲存。",
    endpointRequired: "請先填寫伺服器位址再儲存。",
    modelIdRequired: "請先填寫模型 ID 再儲存。",
    keyRequired: "請先填寫 API 金鑰再儲存。",
    saveFailed: "儲存失敗，請重試。",
    savePartial: "金鑰已儲存，但連線設定未儲存。請再次儲存以完成連線。",
    removeFailed: "未能完整移除這個連線，請重試。",
    env: "偵測到環境變數",
    keychain: "已安全儲存",
    keychainUnavailable: "系統鑰匙圈無法使用",
    secretStored: "已安全儲存",
    secretStoredEnv: "來自環境變數",
    bridgeChecking: "正在檢查桌面連線…",
    unavailable: "打開桌面應用儲存金鑰。",
    bridgeDownTitle: "桌面應用未執行",
    bridgeDownText: "打開應用即可連接服務並儲存金鑰。",
    notConnected: "未連接",
    capabilityText: "文字",
    capabilityImage: "圖像",
    capabilityVideo: "影片",
    capability3d: "3D",
    runtimeTitle: "本地 AI",
    profileTitle: "本機資料目錄",
    profileEmptyText: "打開應用即可定位本機資料。",
    openProfileFolder: "打開",
    openingProfileFolder: "打開中…",
    openProfileFolderFailed: "無法打開本機資料目錄。",
    openProfileFolderOk: "已打開本機資料目錄。",
    modelStoreTitle: "模型目錄",
    runtimeEmptyTitle: "暫無狀態",
    runtimeEmptyText: "打開應用查看本地模型。",
    modelStoreEmptyTitle: "暫無模型目錄狀態",
    modelStoreEmptyText: "你的模型目錄會顯示在這裡。",
    available: "已存在",
    missing: "未發現",
    locked: "金鑰只儲存在本機",
    runtimeAvailable: "已連接",
    runtimeModels: "個模型",
    runtimeProbing: "探測中…",
    systemDetailsTitle: "儲存與連線詳情",
  },
} as const;
