export const lunaToken = {
  color: {
    background: "var(--background)",
    foreground: "var(--foreground)",
    base: "var(--bg-base)",
    surface: "var(--bg-surface)",
    elevated: "var(--bg-elevated)",
    glass: "var(--bg-glass)",
    borderSubtle: "var(--border-subtle)",
    borderActive: "var(--border-active)",
    textPrimary: "var(--text-primary)",
    textSecondary: "var(--text-secondary)",
    textTertiary: "var(--text-tertiary)",
    textMuted: "var(--text-muted)",
    accent: "var(--accent-primary)",
    glow: "var(--accent-glow)",
    gold: "var(--accent-gold)",
    success: "var(--success)",
    warning: "var(--warning)",
    destructive: "var(--destructive)",
    info: "var(--info)",
    scrim: "var(--scrim)",
    scrimStrong: "var(--scrim-strong)",
    scrimHover: "var(--scrim-hover)",
    scrimMedia: "var(--scrim-media)",
    scrimInverse: "var(--scrim-inverse)",
  },
  radius: {
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    card: "var(--radius-card)",
    panel: "var(--radius-panel)",
  },
  shadow: {
    xs: "var(--shadow-xs)",
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    outlineInset: "var(--shadow-outline-inset)",
    insetStrong: "var(--shadow-inset-strong)",
  },
  duration: {
    micro: "var(--motion-micro)",
    control: "var(--motion-control)",
    overlay: "var(--motion-overlay)",
    modal: "var(--motion-modal)",
    surface: "var(--motion-surface)",
    exit: "var(--motion-exit)",
  },
  z: {
    base: "var(--z-base)",
    stage: "var(--z-stage)",
    floating: "var(--z-floating)",
    overlay: "var(--z-overlay)",
    modal: "var(--z-modal)",
    toast: "var(--z-toast)",
  },
} as const;

export const lunaClass = {
  surface: "border border-(--border-subtle) bg-(--bg-surface) text-(--text-primary) shadow-(--shadow-sm)",
  elevated: "border border-(--border-active) bg-(--bg-elevated) text-(--text-primary) shadow-(--shadow-md)",
  glass: "border border-(--border-subtle) bg-(--bg-glass) text-(--text-primary) shadow-(--shadow-outline-inset)",
  mutedText: "text-(--text-muted)",
  secondaryText: "text-(--text-secondary)",
  capsLabel: "text-xs font-semibold uppercase tracking-wide text-(--text-muted)",
  focusRing: "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-2 focus-visible:outline-none",
} as const;
