import type { Locale } from "@/lib/i18n/locale";

export const COPY = {
  en: {
    openingTitle: "Opening canvas",
    openingDescription: "Preparing your layers and editing tools.",
    loadFailedTitle: "Canvas could not load",
    retry: "Retry",
    library: "Library",
    projects: "Projects",
    noLayersTitle: "Refine your generated assets here",
    noLayersDescription:
      "Ask the AI Assistant to create something, or bring an asset over from your Library.",
    noLayersPrimaryCta: "Ask the AI Assistant",
    editActionsTitle: "Edit selected layer",
    agent: "AI Assistant",
    inpaintHere: "Inpaint here",
    removeBg: "Remove BG",
    collapseAgentPanel: "Collapse AI Assistant panel",
    openAgentPanel: "Open AI Assistant panel",
    saving: "Saving…",
    saved: "Saved",
    cancel: "Cancel",
    confirm: "Confirm",
    noBackendTitle: "Connect a generation model in Settings first.",
    noImageEditBackendTitle: "Connect a cloud service that supports image editing.",
    setUpImageEditing: "Set up image editing",
    toastSelectLayerToMask:
      "Select a layer first, then draw a rectangle / ellipse over the area to mask.",
    toastNoMarkerShapes:
      "No marker shapes overlap the selected layer. Draw a rect or ellipse first.",
    promptInpaintTitle: "Describe what to put in the masked region:",
    promptInpaintPlaceholder: "e.g. a vase of fresh tulips",
    toastMaskUploadFailed: "Mask upload failed.",
    toastSelectLayer: "Select a layer first.",
    toastSaveFailed:
      "Couldn't save canvas changes after several tries. Check your connection — your layout is still on screen.",
    toastDeleteLayerFailed: "Couldn't remove the layer. Restoring it from your saved canvas.",
    toastAssetNotOnCanvas: "This image is no longer on the canvas. Add it again from Library.",
    toastRestoreLayerFailed: "Couldn't restore the layer. Add it again from Library.",
    toastRotatedLayerMask:
      "Inpaint doesn't support rotated layers yet. Reset the layer's rotation, then draw the mask again.",
    loadFailedFallback: "Failed to load session.",
  },
  "zh-CN": {
    openingTitle: "正在打开画布",
    openingDescription: "正在准备你的图层和编辑工具。",
    loadFailedTitle: "画布无法加载",
    retry: "重试",
    library: "素材库",
    projects: "项目",
    noLayersTitle: "在这里精修你生成的素材",
    noLayersDescription:
      "让 AI 助手生成一些内容，或从素材库中拖入素材。",
    noLayersPrimaryCta: "向 AI 助手提问",
    editActionsTitle: "编辑所选图层",
    agent: "AI 助手",
    inpaintHere: "在此重绘",
    removeBg: "移除背景",
    collapseAgentPanel: "收起 AI 助手面板",
    openAgentPanel: "打开 AI 助手面板",
    saving: "正在保存…",
    saved: "已保存",
    cancel: "取消",
    confirm: "确认",
    noBackendTitle: "请先在设置中连接一个生成模型。",
    noImageEditBackendTitle: "连接支持图像编辑的云端服务。",
    setUpImageEditing: "设置图像编辑",
    toastSelectLayerToMask: "请先选择一个图层，然后在要遮罩的区域绘制矩形 / 椭圆。",
    toastNoMarkerShapes: "没有标记形状与所选图层重叠。请先绘制矩形或椭圆。",
    promptInpaintTitle: "描述要在遮罩区域中放入的内容：",
    promptInpaintPlaceholder: "例如：一瓶新鲜的郁金香",
    toastMaskUploadFailed: "遮罩上传失败。",
    toastSelectLayer: "请先选择一个图层。",
    toastSaveFailed:
      "多次尝试后仍无法保存画布更改。请检查你的网络连接——你的布局仍显示在屏幕上。",
    toastDeleteLayerFailed: "无法删除图层，已从已保存的画布恢复。",
    toastAssetNotOnCanvas: "这张图片已不在画布上。请从素材库重新添加。",
    toastRestoreLayerFailed: "无法恢复图层，请从素材库重新添加。",
    toastRotatedLayerMask: "局部重绘暂不支持旋转后的图层。请先将图层旋转归零，再绘制遮罩。",
    loadFailedFallback: "加载会话失败。",
  },
  "zh-TW": {
    openingTitle: "正在開啟畫布",
    openingDescription: "正在準備你的圖層和編輯工具。",
    loadFailedTitle: "畫布無法載入",
    retry: "重試",
    library: "素材庫",
    projects: "專案",
    noLayersTitle: "在這裡精修你生成的素材",
    noLayersDescription:
      "讓 AI 助手生成一些內容，或從素材庫中拖入素材。",
    noLayersPrimaryCta: "向 AI 助手提問",
    editActionsTitle: "編輯所選圖層",
    agent: "AI 助手",
    inpaintHere: "在此重繪",
    removeBg: "移除背景",
    collapseAgentPanel: "收合 AI 助手面板",
    openAgentPanel: "開啟 AI 助手面板",
    saving: "正在儲存…",
    saved: "已儲存",
    cancel: "取消",
    confirm: "確認",
    noBackendTitle: "請先在設定中連接一個生成模型。",
    noImageEditBackendTitle: "連接支援圖像編輯的雲端服務。",
    setUpImageEditing: "設定圖像編輯",
    toastSelectLayerToMask: "請先選擇一個圖層，然後在要遮罩的區域繪製矩形 / 橢圓。",
    toastNoMarkerShapes: "沒有標記形狀與所選圖層重疊。請先繪製矩形或橢圓。",
    promptInpaintTitle: "描述要在遮罩區域中放入的內容：",
    promptInpaintPlaceholder: "例如：一瓶新鮮的鬱金香",
    toastMaskUploadFailed: "遮罩上傳失敗。",
    toastSelectLayer: "請先選擇一個圖層。",
    toastSaveFailed:
      "多次嘗試後仍無法儲存畫布變更。請檢查你的網路連線——你的版面仍顯示在螢幕上。",
    toastDeleteLayerFailed: "無法刪除圖層，已從已儲存的畫布還原。",
    toastAssetNotOnCanvas: "這張圖片已不在畫布上。請從素材庫重新加入。",
    toastRestoreLayerFailed: "無法還原圖層，請從素材庫重新加入。",
    toastRotatedLayerMask: "局部重繪暫不支援旋轉後的圖層。請先將圖層旋轉歸零，再繪製遮罩。",
    loadFailedFallback: "載入工作階段失敗。",
  },
} as const satisfies Record<Locale, Record<string, string>>;
